In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [2]:
df = pd.read_csv('train_titanic.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [3]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [4]:
df.dropna(inplace=True)

In [5]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [6]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [7]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [8]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

0.6933333333333332

In [9]:
#Applying Feature Construction

In [10]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [11]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    else:
        # large family
        return 2

In [13]:
X['Family_type'] = X['Family_size'].apply(myfunc)
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [14]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)
#drop these as we have created using these a new col.

In [15]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [16]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))
#accuracy has increased a little

0.7003174603174602

In [17]:
#Feature Splitting

In [18]:
df = pd.read_csv('train_titanic.csv')

In [19]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [23]:
df['Name'].str.split(', ', expand=True)

             0                                           1
0       Braund                             Mr. Owen Harris
1      Cumings  Mrs. John Bradley (Florence Briggs Thayer)
2    Heikkinen                                 Miss. Laina
3     Futrelle          Mrs. Jacques Heath (Lily May Peel)
4        Allen                           Mr. William Henry
..         ...                                         ...
886   Montvila                                 Rev. Juozas
887     Graham                        Miss. Margaret Edith
888   Johnston              Miss. Catherine Helen "Carrie"
889       Behr                             Mr. Karl Howell
890     Dooley                                 Mr. Patrick

[891 rows x 2 columns]

In [25]:
df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)

        0                                       1     2
0      Mr                             Owen Harris  None
1     Mrs   John Bradley (Florence Briggs Thayer)  None
2    Miss                                   Laina  None
3     Mrs           Jacques Heath (Lily May Peel)  None
4      Mr                           William Henry  None
..    ...                                     ...   ...
886   Rev                                  Juozas  None
887  Miss                          Margaret Edith  None
888  Miss                Catherine Helen "Carrie"  None
889    Mr                             Karl Howell  None
890    Mr                                 Patrick  None

[891 rows x 3 columns]

In [26]:
df['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [27]:
df[['Title','Name']]

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [28]:
(df.groupby('Title').mean()['Survived']).sort_values(ascending=False)
#can see survival rate according to salutation, it is giving usefull info

<ipython-input-28-41c5727be791>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  (df.groupby('Title').mean()['Survived']).sort_values(ascending=False)

Title
the Countess    1.000000
Mlle            1.000000
Sir             1.000000
Ms              1.000000
Lady            1.000000
Mme             1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Col             0.500000
Major           0.500000
Dr              0.428571
Mr              0.156673
Jonkheer        0.000000
Rev             0.000000
Don             0.000000
Capt            0.000000
Name: Survived, dtype: float64

In [29]:
#make new col. as survival rate for mrs is 79%
df['Is_Married'] = 0
df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1

<ipython-input-29-0c85a8019a59>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1

In [30]:
df['Is_Married']

0      0
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_Married, Length: 891, dtype: int64